# Generated by Django 5.1.4 on 2025-04-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_color_cartitem_color_product_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Thanh toán khi nhận hàng (COD)'), ('bank_transfer', 'Chuyển khoản ngân hàng'), ('momo', 'Ví điện tử MoMo'), ('zalopay', 'ZaloPay'), ('vnpay', 'VNPAY')], default='cod', max_length=20),
        ),
    ]
