# Generated by Django 5.1.4 on 2025-04-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_profile_address_profile_bio_profile_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.IntegerField(blank=True, default=0, help_text='Phần trăm giảm giá từ 0-100'),
        ),
    ]
