# Generated by Django 5.1.4 on 2025-04-15 22:14

import django.db.models.deletion
from django.db import migrations, models


def update_existing_orders(apps, schema_editor):
    pass  # Bỏ qua việc cập nhật dữ liệu hiện tại

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_discount_percent'),
    ]
    
    operations = [
        # Thêm function để cập nhật dữ liệu hiện tại
        migrations.RunPython(update_existing_orders),
        
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='district_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='ward_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        # Thay đổi các trường hiện có thành blank=True để cho phép giá trị trống
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='ward',
            field=models.CharField(blank=True, max_length=50),
        ),
        # Tạo model District sau khi đã thay đổi trường district trong Order
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='store.province')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        # Tạo model Ward sau khi đã thay đổi trường ward trong Order
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='store.district')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='store.province'),
        ),
    ]
