# Generated by Django 5.1.4 on 2025-04-15 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_district_province_order_district_name_and_more'),
    ]
    
    operations = [
        # Đầu tiên xóa các trường cũ
        migrations.RemoveField(
            model_name='order',
            name='district',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ward',
        ),
        # Thêm các trường Foreign Key mới
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='store.district'),
        ),
        migrations.AddField(
            model_name='order',
            name='ward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='store.ward'),
        ),
    ] 